fix: allow using flag names '--config' or '--matches'
Prefix local variables in generated code to prevent conflicts when clap
file was named the same as a local variable we use to calculate the
defaults here.

```
error[E0599]: no method named `as_mut` found for struct `Utf8PathBuf` in the current scope
```